### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dicej** [bjorn3/browser_wasi_shim#1]
I'm interested in using this library, but I noticed there's no license file and no license specified in package.json.  Would you mind adding one?

**Comment by bjorn3** [comment]
I hadn't bothered with choosing a license. I will add a license file to the repo tomorrow. In any case I hereby license browser_wasi_shim under the following terms:

> Licensed under either of
>
> * Apache License, Version 2.0 ([LICENSE-APACHE](https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
> * MIT license ([LICENSE-MIT](https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/LICENSE-MIT) or http://opensource.org/licenses/MIT)
>
> at your option.
