### ISSUE TITLE
Don't mix ESM import with CJS exports

### ISSUE THREAD

**Issue by brandonchinn178** [bjorn3/browser_wasi_shim#12]
`index.js` currently has both `import ... from ...` statements and `module.exports = ...` syntaxes, which are two different import systems.

The current problem I'm facing is I'm trying to bundle a script importing `@bjorn3/browser_wasi_shim` with webpack, and it fails at buildtime when importing with `require()` (because `@bjorn3/browser_wasi_shim`'s `package.json` has an `exports` field that says `index.js` is only importable via `import` statements) and fails at runtime when importing with `import` (because webpack throws an error if an ESM module tries to set `module.exports`)

https://stackoverflow.com/a/42450109/4966649

Repro:
```bash
mkdir src
echo 'import { WASI } from "@bjorn3/browser_wasi_shim"' > src/index.js
npm install webpack webpack-cli @bjorn3/browser_wasi_shim
npx webpack
node dist/main.js
```
Expected clean exit, got `Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead`

---

Less importantly, it would be great if `@bjorn3/browser_wasi_shim` could provide a UMD build so that it's easy to just do something like

```html
<script src="//unpkg.com/@bjorn/browser_wasi_shim"></script>
<script>
  const { WASI } = window['@bjorn/browser_wasi_shim']
  new WASI(...)
</script>
```

For now, I can just bundle the package myself with webpack.

**Comment by bjorn3** [comment]
Thanks for the report! I'm currently rather busy, but I will try to get to this tomorrow or thursday.
