### ISSUE TITLE
Example in README does not typecheck

### ISSUE THREAD

**Issue by jakebailey** [bjorn3/browser_wasi_shim#22]
I'm trying to use this package, but, copying the code from the readme leaves me with code that doesn't compile.

Is this still a valid example for a simple usage?

**Comment by jakebailey** [comment]
Seems like it actually needs to pass `OpenFile`, not just `File`, otherwise it crashes at runtime.

**Comment by bjorn3** [comment]
Thanks! `OpenFile` is indeed necessary. Pushed a fix.
