### ISSUE TITLE
Reduce and/or configure `console.log` verbosity

### ISSUE THREAD

**Issue by dicej** [bjorn3/browser_wasi_shim#3]
Currently, there are a lot of `console.log` statements in wasi.js and elsewhere, which is nice for debugging but should probably be turned off for a release scenario.  I'm not sure what the current best practice is for this kind of thing in the JS world, so I'm open to suggestions about how to do it.

**Comment by bjorn3** [comment]
I agree. I think all those console.log calls should be replaced by an optional strace like Proxy.

**Comment by bjorn3** [comment]
As of the latest commit you can now remove the `strace` wrapper call at https://github.com/bjorn3/browser_wasi_shim/blob/81199679beea323c53a245945208ebd5dbd9612b/rustc.html#L109 to remove almost all logging.
