### ISSUE TITLE
Consider moving rustc.html (and xterm dependencies) to separate project

### ISSUE THREAD

**Issue by dicej** [bjorn3/browser_wasi_shim#4]
In order to make this library a bit more streamlined, I'd suggest removing the `xterm` and `xterm-addon-fit` dependencies since they're not needed by the library itself.  Would it make sense to split this repo into two separate projects, one for the WASI shim itself and another for the rustc-in-a-browser app?

**Comment by bjorn3** [comment]
rustc.html is an example and test. I think it should stay in the same repo, but moving it to a separate examples directory would work.

**Comment by dicej** [comment]
> rustc.html is an example and test. I think it should stay in the same repo, but moving it to a separate examples directory would work.

That's fine with me.  To be clear, I'm less concerned about rustc.html itself and more concerned about the `xterm` and `xterm-addon-fit` deps being pulled into any project that uses `browser_wasi_shim`.
