### ISSUE TITLE
bug: Logic for checking for directory is incorrect

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [bjorn3/browser_wasi_shim#47]
The condition should be ` entry.stat().filetype === wasi.FILETYPE_DIRECTORY ` to check if the entry filetype is actually a directory.
https://github.com/bjorn3/browser_wasi_shim/blob/51f5c2988e6fa13c0a8643f8bf2c36e31bf326fe/src/fs_fd.ts#L283

**Comment by bjorn3** [comment]
The logic here is if we want to open a directory (`oflags` contains `OFLAGS_DIRECTORY`), but the target is not directory (`filetype` is not `FILETYPE_DIRECTORY`), then return `ERRNO_ISDIR` as error.

**Comment by bjorn3** [comment]
Looks like the comment and error number are wrong though. It should be `ERRNO_NOTDIR`: https://github.com/bytecodealliance/wasmtime/blob/6aaf682894cf0ed974e2aa86fddf5d949af54add/crates/wasi-common/cap-std-sync/src/dir.rs#L95-L96
