### ISSUE TITLE
Migrate from flow to typescript

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/browser_wasi_shim#5]
I originally chose flow over typescript because it allows putting type definitions in comments and as such doesn't require a separate compilation step. Unfortunately flow has several limitations including not supporting bigints and some incorrect builtin type declarations. As such I think using typescript is better in the long term.

**Comment by bjorn3** [comment]
@dicej What tool would you recommend for stripping type declarations from typescript files to make them valid javascript files? I know there are a whole lot of them. Too many IMHO.

**Comment by dicej** [comment]
Honestly it's been a while since I did anything serious in either TS or JS, so my knowledge may be out-of-date.  Last time I worked on a TS project, we just used the official `tsc` compiler from the `typescript` NPM package.  You'd need to use that anyway to actually do type checking, and it will produce a JS file for each TS file you give it.

**Comment by bjorn3** [comment]
I see. Unfortunately tsc is way too slow. My editor already does typechecking and having to wait 7 seconds after any change before I can refresh the page is way too much.

**Comment by dicej** [comment]
Fair enough.  The "Working with TypeScript-compatible transpilers" section of https://www.typescriptlang.org/download might be helpful.  I don't have any experience with anything but `tsc`, unfortunately.

**Comment by bhelx** [comment]
The concern about slowness is fair from an internal perspective, but externally I'm not sure if there is any typing info you can get from this library. If you don't want to do a re-write in TS, I could contribute some type definition files. Or perhaps there is a way to generate d.ts files from flow annotated code.

**Comment by bjorn3** [comment]
I'm open to having typescript type definitions for the public api. I don't expect there is a way to generate typescript type definitions from flow annotated code, but I'm happy to be proven wrong.

**Comment by bhelx** [comment]
My concern with definition files is just the maintenance burden. I don't think there is an automated way to check that it's drifting. But if the public API remains small, then it might not be that much concern. I'll look into it.
