### ISSUE TITLE
Circular dependency between `fs_core.ts` <-> `fs_fd.ts`

### ISSUE THREAD

**Issue by kateinoigakukun** [bjorn3/browser_wasi_shim#58]
Currently `fs_core.ts` and `fs_fd.ts` import each other. Fortunately it does not cause any problem at the moment, but Rollup conservatively warns about this. (I faced it while changing default bundled WASI implementation of ruby.wasm: https://github.com/ruby/ruby.wasm/pull/332)

```console
$ npx rollup ./dist/index.js -o /dev/null
./dist/index.js → ../../../../../../dev/null...
(!) Circular dependency
dist/fs_core.js -> dist/fs_fd.js -> dist/fs_core.js
created ../../../../../../dev/null in 174ms
```

There are some options to address this issue. Which option do you like, @bjorn3? I personally prefer 2. since it is the simplest and does not change any public API.

1. Just ignore the warning or fix rollup to produce more precise cycle detection
2. Merge `fs_core.ts` and `fs_fd.ts`
3. Re-organize `fs_core.ts` and `fs_fd.ts`'s API to avoid cycle

**Comment by bjorn3** [comment]
Forgot to reply here. I think merging `fs_core.ts` and `fs_fd.ts` is fine. Or maybe separate files and directories instead. There shouldn't be a cyclic dependency between those except maybe through type hints.
