### ISSUE TITLE
args_sizes_get has different interface

### ISSUE THREAD

**Issue by peter-jerry-ye** [bjorn3/browser_wasi_shim#59]
Hello. First of all, thanks for the great project.

I found that in this repo (and in deno/std/wasi which is deprecated and removed), the interface of `args_size_get` is `args_sizes_get(argc: number, argv_buf_size: number): number`. However, [the standard of wasi](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md#-args_sizes_get---resultsize-size-errno) has the interface as `args_sizes_get() -> Result<(size, size), errno>`

May I ask why there's the difference?

**Comment by bjorn3** [comment]
`Result` and tuples are not actually representable in webassembly. What ends up happening is that behind the scenes a signature like `() -> Result<(size, size), errno>` is lowered into `(i32, i32) -> i32`. In case of a success the `size` values are written to the memory pointed to by the pointers passed to `args_sizes_get` as `i32` and `0` is returned from the function. In case of an error, the actual error number is returned instead.

See also https://docs.rs/wasi/latest/src/wasi/lib_generated.rs.html#1219-1237 where the user facing `args_sizes_get() -> Result<(size, size), errno>` is lowered into a call to `args_sizes_get(i32, i32) -> i32`.

**Comment by peter-jerry-ye** [comment]
Thank you very much for your kind explanation.

在 2023年12月13日，01:05，bjorn3 ***@***.***> 写道：

﻿

I'm going to close this as I assume my preview comment cleared up the confusion you had. If not, please let me know.
