### ISSUE TITLE
Usage example doesn't work

### ISSUE THREAD

**Issue by Averave** [bjorn3/browser_wasi_shim#68]
> Uncaught SyntaxError: The requested module '@bjorn3/browser_wasi_shim' does not provide an export named 'ConsoleStdout'

The usage example tells you to install from NPM and use code which imports `ConsoleStdout`. However, the NPM package doesn't have any code for `ConsoleStdout` because the changes from #67 were not published to NPM.

**Comment by bjorn3** [comment]
Published #67 as v0.2.19.
